const serviceFilters = [
  {
    id: 1,
    label: "Engineering",
    value: "engineering",
  },
  {
    id: 2,
    label: "Residential Design",
    value: "residential",
  },
  {
    id: 3,
    label: "Commercial Design",
    value: "commercial",
  },
  {
    id: 4,
    label: "Industrial Design",
    value: "industrial",
  },
  {
    id: 5,
    label: "Infrastructure",
    value: "infrastructure",
  },
  {
    id: 6,
    label: "Vastu Consultation",
    value: "vastu",
  },
  {
    id: 7,
    label: "Property Valuation",
    value: "valuation",
  },
];

export default serviceFilters;
