const projectFilters = [
  {
    id: 1,
    label: "All Concepts",
    value: "all",
  },
  {
    id: 2,
    label: "Residential",
    value: "residential",
  },
  {
    id: 3,
    label: "Commercial",
    value: "commercial",
  },
  {
    id: 4,
    label: "Infrastructure",
    value: "infrastructure",
  },
  {
    id: 5,
    label: "Sustainable",
    value: "sustainable",
  },
];

export default projectFilters;
